
root: /

Home: /
Archives: /archives
About: /about

language: en

author: xiaoyang (theme author fuzhouxx Dong)
description: 咸鱼一条

disqus:
  enable: true
  shortname: xiaoyang

google_site_verification:
google_analytics:
